version: '3.7'

networks:
  fonoster:

services:
  instrumentation:
    image: fonoster/instrumentation:latest
    ports:
      - 30001:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.instrumentation.entrypoints=websecure"
      - "traefik.http.services.instrumentation.loadbalancer.server.port=3000"
      - "traefik.http.routers.instrumentation.rule=PathPrefix(`/instrumentation`)"
    volumes:
      - ${CONFIG}/config:/home/fonoster/.fonoster/config
      - ${CONFIG}/instrumentation.json:/home/fonoster/.fonoster/instrumentation.json
    networks:
      fonoster:
